#!/bin/sh

if [[ $1 = *y* ]]; then  curl -L "covid19cli.now.sh" -o ~/.cache/corona.tmp && sed -n "1,8p;15p" ~/.cache/corona.tmp > ~/.cache/corona && rm -r ~/.cache/corona.tmp ;fi

case $1 in
		 '')
				cat	~/.cache/corona
				;;
		*ma*)
				grep -i  ~/.cache/corona
				;;
esac

