#!/bin/sh

# chafa -d 5 --clear -w 9 -c full --symbols braille --fill braille https://radar.weather.gov/lite/N0R/BOX_loop.gif

while true; do
chafa -d 0 --clear -w 5 -c full --symbols braille --fill braille ~/.cache/wether/radar.gif
    read -t 0.25 -N 1 input
    if [[ $input = "q" ]] || [[ $input = "Q" ]]; then
# The following line is for the prompt to appear on a new line.
        echo
				clear
        break
    fi
done

