#!/bin/sh

id=$(echo -e "point\ntrack\nboth" | dmenu -i -p 'togele')

case $id in
		point)
				device="TPPS/2 IBM TrackPoint"
				;;
		track)
				device="Synaptics TM3276-022"
				;;
		both)
				device1="TPPS/2 IBM TrackPoint"
				device2="Synaptics TM3276-022"
				state1=`xinput list-props "$device1" | grep "Device Enabled" | grep -o "[01]$"`
				state2=`xinput list-props "$device2" | grep "Device Enabled" | grep -o "[01]$"`

				if [ "$state1" -eq '1' ];then
						xinput --disable "$device1"
				else
						xinput --enable "$device1"
				fi

				if [ "$state2" -eq '1' ];then
						xinput --disable "$device2"
				else
						xinput --enable "$device2"
				fi
				exit
				;;
		*)
				exit
				;;
esac

state=`xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$"`

if [ "$state" -eq '1' ];then
  xinput --disable "$device"
else
  xinput --enable "$device"
fi
