#!/bin/sh

if [ $(cat /sys/class/net/w*/operstate 2>/dev/null) = up ]; then 

curl 'v2d.wttr.in/Ashfield,Ma?Qm' > ~/.cache/wether/visual

curl 'wttr.in/Ashfield,Ma?mQ0' > ~/.cache/wether/single

curl 'wttr.in/Ashfield,Ma?nm' > ~/.cache/wether/long

curl 'wttr.in/Ashfield,Ma?m' > ~/.cache/wether/long-full

curl 'https://radar.weather.gov/lite/N0R/BOX_loop.gif' > ~/.cache/wether/radar.gif; 
else exit ; fi
