#!/bin/sh

# if [ $(cat /sys/class/net/wl*/operstate 2>/dev/null) = *up ]; then 
	/usr/bin/mailsync;
	/usr/bin/touch /home/silas/.cache/mail; 
	/usr/bin/pkill -RTMIN+5 dwmblocks;
# else exit ; fi

# * * * * * /bin/sh /usr/local/bin/mw -y silas.anderson00@gmail.com && /usr/bin/touch /home/silas/.cache/mail && /usr/bin/pkill -RTMIN+5 dwmblocks
